version: '3'

services:

  # NEXUS_USER= NEXUS_PASSWORD= docker-compose up deploy
  deploy:
    image: 'gradle:jdk15'
    command: ["./gradlew", "build", "publish", "-Pargs=${NEXUS_USER} ${NEXUS_PASSWORD}"]
    working_dir: '/home/gradle/project'
    volumes:
      - './:/home/gradle/project'

  # docker-compose run build
  build:
    image: 'gradle:jdk15'
    command: ["./gradlew", "build", "test"]
    working_dir: '/home/gradle/project'
    volumes:
      - './:/home/gradle/project'