version: '3'

services:
  deploy:
    image: 'gradle:7.0.2-jdk16'
    command: ["./gradlew", "publish", "-Pargs=${NEXUS_USER} ${NEXUS_PASSWORD}"]
    working_dir: '/home/gradle/project'
    volumes:
      - './:/home/gradle/project'

  # docker-compose up test
  test:
    image: 'gradle:7.0.2-jdk16'
    command: ["./gradlew", "test"]
    working_dir: '/home/gradle/project'
    volumes:
      - './:/home/gradle/project'