name: Java CI with Gradle
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: pwd
    - name: Run tests on Docker
      run: docker run -v $(pwd):/project gradle:jdk15 sh -c 'cd /project; ./gradlew test; ls -l ./jumpaku-curves-fsc-test/build/resources/test/jumpaku/curves/fsc/test/snap/conicsection/;'
