name: Java CI with Gradle
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ls -l /root/jumpaku-curves-fsc-test/src/test/resources/jumpaku/curves/fsc/test/snap/conicsection/
    - name: Run tests on Docker
      run: docker run -v $(pwd):/project gradle:jdk15 sh -c 'cd /project; ./gradlew test'
